export enum TaskStatus {
	PENDING = 'pending',
	COMPLETED = 'completed'
}

export class TaskEntity {
	constructor(
		public readonly id: string,
		public readonly title: string,
		public readonly description: string | null,
		public readonly status: TaskStatus,
		public readonly userId: string,
		public readonly createdAt: Date = new Date(),
		public readonly updatedAt: Date = new Date()
	) {}

	static create(title: string, description: string | null, userId: string): TaskEntity {
		return new TaskEntity(
			'', // ID will be generated by the database
			title,
			description,
			TaskStatus.PENDING,
			userId,
			new Date(),
			new Date()
		)
	}

	complete(): TaskEntity {
		return new TaskEntity(
			this.id,
			this.title,
			this.description,
			TaskStatus.COMPLETED,
			this.userId,
			this.createdAt,
			new Date()
		)
	}

	update(title?: string, description?: string): TaskEntity {
		return new TaskEntity(
			this.id,
			title ?? this.title,
			description ?? this.description,
			this.status,
			this.userId,
			this.createdAt,
			new Date()
		)
	}
}
