export class PermissionEntity {
	constructor(
		public readonly id: string,
		public readonly name: string,
		public readonly description?: string,
		public readonly createdAt: Date = new Date(),
		public readonly updatedAt: Date = new Date()
	) {}

	static create(name: string, description?: string): PermissionEntity {
		return new PermissionEntity(
			'', // ID will be generated by the database
			name,
			description,
			new Date(),
			new Date()
		)
	}
}
