export class UserEntity {
	constructor(
		public readonly id: string,
		public readonly name: string,
		public readonly email: string,
		public readonly password: string,
		public readonly isActive: boolean = true,
		public readonly createdAt: Date = new Date(),
		public readonly updatedAt: Date = new Date()
	) {}

	static create(name: string, email: string, password: string): UserEntity {
		return new UserEntity(
			'', // ID will be generated by the database
			name,
			email,
			password,
			true,
			new Date(),
			new Date()
		)
	}

	updatePassword(newPassword: string): UserEntity {
		return new UserEntity(
			this.id,
			this.name,
			this.email,
			newPassword,
			this.isActive,
			this.createdAt,
			new Date()
		)
	}

	deactivate(): UserEntity {
		return new UserEntity(
			this.id,
			this.name,
			this.email,
			this.password,
			false,
			this.createdAt,
			new Date()
		)
	}
}
